name: CI

on: [push, pull_request]

jobs:

  test-valgrind-test:
    runs-on: ubuntu-latest
    timeout-minutes: 14400
    steps:
      - name: prep
        run: |
          echo "GITHUB_REPOSITORY=${{github.event.inputs.use_repo}}" >> $GITHUB_ENV
          echo "GITHUB_HEAD_REF=${{github.event.inputs.use_git_ref}}" >> $GITHUB_ENV
          echo "skipjobs: ${{github.event.inputs.skipjobs}}"
          echo "skiptests: ${{github.event.inputs.skiptests}}"
          echo "test_args: ${{github.event.inputs.test_args}}"
          echo "cluster_test_args: ${{github.event.inputs.cluster_test_args}}"
      - uses: actions/checkout@v3
        with:
          repository: ${{ env.GITHUB_REPOSITORY }}
          ref: ${{ env.GITHUB_HEAD_REF }}
      - name: make
        run: make valgrind REDIS_CFLAGS='-Werror -DREDIS_TEST'
      - name: testprep
        run: |
          sudo apt-get update
          sudo apt-get install tcl8.6 tclx valgrind -y
      - name: test
        run: ./runtest --valgrind --no-latency --verbose --clients 1 --timeout 2400 --dump-logs --skipunit unit/cluster/replica-migration-2 --skipunit unit/cluster/replica-migration-3

  test-sanitizer-address:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      # build with TLS module just for compilation coverage
      run: make SANITIZER=address REDIS_CFLAGS='-Werror -DDEBUG_ASSERTIONS' BUILD_TLS=module
    - name: testprep
      run: sudo apt-get install tcl8.6 tclx -y
    - name: test
      run: ./runtest --verbose --tags -slow --dump-logs --skipunit unit/cluster/replica-migration-2 --skipunit unit/cluster/replica-migration-3
